name: ac_chat_example
description: Example app demonstrating ac_chat.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  ac_chat:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
