name: ac_sql
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  autocode:
    path: './../autocode'
  ac_data_dictionary:
    path: './../ac_data_dictionary'
  ac_extensions:
    path: './../ac_extensions'
  ac_mirrors:
    path: './../ac_mirrors'
  mysql_dart: ^1.0.0
  path: ^1.9.1
  postgres: ^3.5.6
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
