name: ac_chat
description: A complete Flutter chat UI toolkit, flexible and pluggable, supporting mobile, desktop, and web.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  autocode:
    path: './../autocode'
  ac_extensions:
    path: './../ac_extensions'
  ac_mirrors:
    path: './../ac_mirrors'

  emoji_picker_flutter: ^4.5.3
  sticky_headers: ^0.3.0+2
  intl: ^0.20.3
  audio_waveforms: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: