name: ac_patches
description: Production-grade self-hosted Flutter Over-The-Air (OTA) patching platform.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: ac_patches_android
      windows:
        default_package: ac_patches_windows

dependencies:
  flutter:
    sdk: flutter
  ac_patches_core:
    path: ../ac_patches_core
  ac_patches_format:
    path: ../ac_patches_format
  ac_patches_updater:
    path: ../ac_patches_updater
  ac_patches_android:
    path: ../ac_patches_android
  ac_patches_windows:
    path: ../ac_patches_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
