name: autocode
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  encrypt: ^5.0.3
  intl: ^0.20.2
  uuid: any
  ac_extensions:
    path: './../../packages/ac_extensions'
  ac_mirrors:
    path: './../../packages/ac_mirrors'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
